version: "3"
services:
  express_server:
    image: codeandcoffee.azurecr.io/express-server:latest 
    build: .
    ports:
      - "3000:3000"
      - "9955:9955"
    networks: 
      - app_server_bridge
  redis_server:
    image: loadingdock.azurecr.io/redis:latest
    # env_file:
    #   - .env
    # environment:
    #   - REDIS_PWD=${REDIS_PWD}
    # build:
    #   dockerfile: Redis.Dockerfile
    #   context: .
    ports:
      - "6379:6379"
    networks: 
      - app_server_bridge
networks:
  app_server_bridge:
    driver: bridge
