version: "3"
services:
  express_server:
    image: loadingdock.azurecr.io/express-server:latest 
    build: .
    ports:
      - "3000:3000"
    networks: 
      - app_server_bridge
  redis_server:
    image: redis
    build:
      dockerfile: Redis.Dockerfile
      context: .
    ports:
      - "6379:6379"
    networks: 
      - app_server_bridge
    env_file:
      - .env
    environment:
      - REDIS_PWD=${REDIS_PWD}
networks:
  app_server_bridge:
    driver: bridge
